'use client';

import { useEffect, useState } from 'react';
import { Loader2, RefreshCw, X } from 'lucide-react';
import { FormInput } from '../forms/FormInput';
import { FormTextarea } from '../forms/FormTextarea';
import { Button } from '../forms/Button';
import { slugify } from '../../utils/slugify';
import { checkLinkSlugUniqueness } from '../../utils/linksService';
import {
  DESCRIPTION_MAX_LENGTH,
  hasErrors,
  randomSlugToken,
  validateLinkForm,
} from '../../utils/validateLinkForm';
import { SITE_URL } from '../../config/site';
import type { LinkFormErrors, NewLinkInput } from '../../types/links';

interface NewLinkCardProps {
  onCreate: (input: NewLinkInput) => Promise<void>;
  onCancel: () => void;
}

/**
 * The creation card.
 *
 * It lives entirely in local state until the first valid save. Inserting a row
 * up front would need placeholder values the NOT NULL columns won't accept, and
 * an abandoned creation would leave a junk link squatting a slug — which
 * matters here more than usual, because slugs are immutable once they exist.
 */
export function NewLinkCard({ onCreate, onCancel }: NewLinkCardProps) {
  const [name, setName] = useState('');
  const [slug, setSlug] = useState('');
  const [slugTouched, setSlugTouched] = useState(false);
  const [destinationUrl, setDestinationUrl] = useState('');
  const [description, setDescription] = useState('');
  const [errors, setErrors] = useState<LinkFormErrors>({});
  const [saving, setSaving] = useState(false);
  const [checkingSlug, setCheckingSlug] = useState(false);

  // The slug follows the name until the moment it is edited or regenerated by
  // hand, after which it stops moving on its own.
  useEffect(() => {
    if (!slugTouched) setSlug(slugify(name));
  }, [name, slugTouched]);

  const setError = (field: keyof LinkFormErrors, message?: string) =>
    setErrors((prev) => ({ ...prev, [field]: message }));

  const handleSlugBlur = async () => {
    if (!slug) return;
    setCheckingSlug(true);
    try {
      const free = await checkLinkSlugUniqueness(slug);
      if (!free) setError('slug', 'That slug is already taken');
    } finally {
      setCheckingSlug(false);
    }
  };

  const handleSave = async () => {
    const values = { name, slug, destinationUrl, description, expiresAt: '', maxClicks: '' };
    const found = validateLinkForm(values);

    if (!found.slug) {
      const free = await checkLinkSlugUniqueness(slug);
      if (!free) found.slug = 'That slug is already taken';
    }

    setErrors(found);
    if (hasErrors(found)) return;

    setSaving(true);
    try {
      await onCreate({
        name: name.trim(),
        slug,
        destinationUrl: destinationUrl.trim(),
        description: description.trim() || null,
      });
    } catch (err) {
      setErrors({ slug: err instanceof Error ? err.message : 'Could not create this link' });
    } finally {
      setSaving(false);
    }
  };

  return (
    <article className="relative bg-white border-2 border-black rounded-lg shadow-lg">
      <div className="p-5 space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-black">New link</h2>
          <button
            type="button"
            onClick={onCancel}
            aria-label="Discard new link"
            className="p-1.5 rounded-lg text-neutral-400 hover:text-gray-700 hover:bg-gray-100 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        <FormInput
          label="Name"
          required
          autoFocus
          value={name}
          onChange={(e) => setName(e.target.value)}
          onBlur={() => setError('name', validateLinkForm({ name, slug, destinationUrl, description, expiresAt: '', maxClicks: '' }).name)}
          error={errors.name}
          placeholder="Business card"
        />

        <div>
          <label htmlFor="new-link-slug" className="block text-sm font-medium text-black mb-2">
            Slug<span className="text-red-500 ml-1">*</span>
          </label>
          <div className="flex items-stretch gap-2">
            <span className="inline-flex items-center px-3 bg-neutral-100 border border-neutral-300 rounded-lg text-sm text-neutral-500 font-mono whitespace-nowrap">
              {SITE_URL.replace(/^https?:\/\//, '')}/r/
            </span>
            <input
              id="new-link-slug"
              value={slug}
              onChange={(e) => {
                setSlugTouched(true);
                setSlug(e.target.value);
                setError('slug', undefined);
              }}
              onBlur={handleSlugBlur}
              placeholder="business-card"
              className={`flex-1 min-w-0 px-4 py-3 border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 transition-all ${
                errors.slug
                  ? 'border-red-500 focus:ring-red-500'
                  : 'border-neutral-300 focus:ring-black focus:border-transparent'
              }`}
            />
            <button
              type="button"
              onClick={() => {
                setSlugTouched(true);
                setSlug(randomSlugToken());
                setError('slug', undefined);
              }}
              title="Use a random token instead"
              aria-label="Generate a random slug"
              className="px-3 border border-neutral-300 rounded-lg text-neutral-500 hover:text-black hover:bg-neutral-50 transition-colors flex-shrink-0"
            >
              {checkingSlug ? <Loader2 size={16} className="animate-spin" /> : <RefreshCw size={16} />}
            </button>
          </div>
          {errors.slug ? (
            <p className="mt-2 text-sm text-red-600">{errors.slug}</p>
          ) : (
            <p className="mt-2 text-sm text-neutral-500">
              Permanent once saved — printed codes depend on it.
            </p>
          )}
        </div>

        <FormInput
          label="Destination URL"
          required
          type="url"
          value={destinationUrl}
          onChange={(e) => setDestinationUrl(e.target.value)}
          onBlur={() => setError('destinationUrl', validateLinkForm({ name, slug, destinationUrl, description, expiresAt: '', maxClicks: '' }).destinationUrl)}
          error={errors.destinationUrl}
          placeholder="https://example.com/where-it-goes"
        />

        <FormTextarea
          label="Description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          error={errors.description}
          maxLength={DESCRIPTION_MAX_LENGTH}
          showCharCount
          rows={2}
          placeholder="A short note to yourself about where this link lives."
        />

        <div className="flex justify-end gap-3 pt-1">
          <Button variant="ghost" size="sm" onClick={onCancel} disabled={saving}>
            Cancel
          </Button>
          <Button variant="primary" size="sm" onClick={handleSave} loading={saving}>
            Create link
          </Button>
        </div>
      </div>
    </article>
  );
}
